# Generated by Django 4.2.9 on 2024-07-09 12:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('lobby_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num', models.IntegerField(default=0)),
                ('round', models.IntegerField(default=1)),
                ('player1', models.CharField(default='', max_length=100)),
                ('player2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('winner', models.CharField(blank=True, max_length=15, null=True)),
                ('score_player_1', models.IntegerField(default=0)),
                ('score_player_2', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('timer', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('max_players', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(9)])),
                ('started', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('max_round', models.IntegerField(default=1)),
                ('current_round', models.IntegerField(default=1)),
                ('receipt_address', models.CharField(default='0x0', max_length=100)),
                ('matchups', models.ManyToManyField(blank=True, to='tournaments.tournamentmatch')),
                ('participants', models.ManyToManyField(blank=True, related_name='joined_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
