# Generated by Django 4.2.9 on 2024-05-15 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='host',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='password',
        ),
    ]
