# Generated by Django 4.2.9 on 2024-05-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_remove_tournament_host_remove_tournament_is_private_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
