# Generated by Django 4.2.9 on 2024-04-02 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_tournament_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='score_to_win',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
            preserve_default=False,
        ),
    ]
