# Generated by Django 4.2.9 on 2024-04-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
