# Generated by Django 4.2.9 on 2024-02-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='player1Present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='player2Present',
            field=models.BooleanField(default=False),
        ),
    ]
