# Generated by Django 4.2.9 on 2024-05-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
