# Generated by Django 4.2.9 on 2024-03-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leaderboard',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
