# Generated by Django 4.2.9 on 2024-04-18 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='n_games_played',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='title',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='winrate',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar.jpg', upload_to='profile_avatars'),
        ),
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='users.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='n_games_played',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='winrate',
            field=models.DecimalField(decimal_places=4, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
