# Generated by Django 4.2.9 on 2024-05-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_n_games_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tournament_username',
            field=models.CharField(default='Lusomowaduwa', max_length=25, unique=True),
        ),
    ]
