# Generated by Django 4.2.9 on 2024-04-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_avatar_alter_customuser_bio_profile'),
        ('users', '0008_alter_customuser_avatar'),
    ]

    operations = [
    ]
