# Generated by Django 4.2.9 on 2024-05-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_customuser_tournament_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tournament_username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='ournament_username',
            field=models.CharField(default='', max_length=25, unique=True),
        ),
    ]
