# Generated by Django 4.2.9 on 2024-05-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_customuser_tournament_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='ournament_username',
            new_name='tournament_username',
        ),
    ]
