# Use the official Python image as the base image
FROM python:3.8

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY ./requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Django application code to the container
COPY ./my_app /app/

# Expose port 8000 for Django
EXPOSE 8000

# Command to run Django development server
CMD ["sh", "-c", "python app.py"]
