# Generated by Django 4.2.9 on 2024-07-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(default='', max_length=25)),
                ('to_user', models.CharField(default='', max_length=25)),
            ],
        ),
    ]
