# Generated by Django 4.2.9 on 2024-05-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactionrequest',
            name='status',
        ),
    ]
