# Generated by Django 4.2.9 on 2024-03-20 09:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0003_alter_friendrequest_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendRequest',
            new_name='InteractionRequest',
        ),
    ]
