FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir -p /code/static
COPY . code
WORKDIR /code
COPY requirements.txt code/requirements.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install django-bootstrap-v5

EXPOSE 8000

COPY ./entrypoint.dev.sh .
CMD ["sh","entrypoint.dev.sh"]