from .register import *
from .login_view import *
from .logout_view import *
from .update_profile_username import *
from .update_profile_bio import *
from .update_profile_password import *
from .update_profile_picture import *
from .update_email import *
from .get_csrf_token import *
from .get_user_datas import *
from .check_user_logged_in import *
from .email_available import *
from .confirm_email import *
from .confirm_new_email import *
from .pong_app_AI import game_state_view
from .pong_app_AI import action_view
from .pong_app_AI import reset_game_view
from .pong_app_AI import reward_view