# Generated by Django 4.2.9 on 2024-07-09 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby_id', models.CharField(default='default', editable=False, max_length=100)),
                ('player1', models.CharField(default='', max_length=100, null=True)),
                ('player2', models.CharField(default='', max_length=100, null=True)),
                ('player1_average_exchange', models.IntegerField(default=0)),
                ('player2_average_exchange', models.IntegerField(default=0)),
                ('winner', models.CharField(default='', max_length=100)),
                ('loser', models.CharField(default='', max_length=100)),
                ('player1_score', models.IntegerField(default=0)),
                ('player2_score', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
