# Generated by Django 4.2.9 on 2024-07-10 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby_id', models.CharField(default='default', editable=False, max_length=100)),
                ('player1_average_exchange', models.IntegerField(default=0)),
                ('player2_average_exchange', models.IntegerField(default=0)),
                ('player1_score', models.IntegerField(default=0)),
                ('player2_score', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('loser', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='loser', to=settings.AUTH_USER_MODEL)),
                ('player1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='player2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
