# Generated by Django 4.2.9 on 2024-05-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player1_average_exchange',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_average_exchange',
            field=models.IntegerField(default=0),
        ),
    ]
