FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY .. code
WORKDIR /code

RUN mkdir -p /code/static
COPY requirements.txt code/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r code/requirements.txt
RUN pip install django-bootstrap-v5

EXPOSE 8000

COPY ./entrypoint.dev.sh /code/entrypoint.dev.sh
CMD ["sh","docker/entrypoint.dev.sh"]