FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir -p /code/static
COPY requirements.txt code/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r code/requirements.txt
RUN pip install django-extensions Werkzeug

COPY .. code
WORKDIR /code

COPY ./entrypoint.dev.sh /code/entrypoint.dev.sh
CMD ["sh","docker/entrypoint.dev.sh"]