FROM python:3.10


RUN mkdir -p /code/staticfiles

COPY requirements.txt code/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r code/requirements.txt

RUN apt-get update
RUN apt-get install -y cron

COPY ./entrypoint.prod.sh /code/entrypoint.prod.sh

ARG CACHEBUST
RUN echo $CACHEBUST
COPY .. /code
WORKDIR /code
CMD ["sh","docker/entrypoint.prod.sh"]