# Use the official Nginx image as the base image
FROM nginx:latest

# Copy the Bootstrap frontend files to the Nginx html directory
COPY ./ /usr/share/nginx/html

# Expose port 80
EXPOSE 8080

# Command to start Nginx
COPY nginx.config /etc/nginx/conf.d/default.conf
COPY --from=base build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
